# Generated by Django 3.2.8 on 2021-10-30 11:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArgoBbp',
            fields=[
                ('platform_number', models.IntegerField(primary_key=True, serialize=False)),
                ('cycle_number', models.IntegerField()),
                ('pressure', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True), size=None)),
                ('cpressure', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True), size=None)),
                ('qpressure', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1, null=True), size=None)),
                ('backunknown', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True), size=None)),
                ('cbackunknown', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True), size=None)),
                ('qbackunknown', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1, null=True), size=None)),
                ('back470', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True), size=None)),
                ('cback470', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True), size=None)),
                ('qback470', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1, null=True), size=None)),
                ('back532', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True), size=None)),
                ('cback532', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True), size=None)),
                ('qback532', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1, null=True), size=None)),
                ('back700', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True), size=None)),
                ('cback700', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True), size=None)),
                ('qback700', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1, null=True), size=None)),
            ],
            options={
                'db_table': 'argobbp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArgoCdom',
            fields=[
                ('platform_number', models.IntegerField(primary_key=True, serialize=False)),
                ('cycle_number', models.IntegerField()),
                ('pressure', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True), size=None)),
                ('cpressure', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True), size=None)),
                ('qpressure', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1, null=True), size=None)),
                ('cdom', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True), size=None)),
                ('ccdom', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True), size=None)),
                ('qcdom', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1, null=True), size=None)),
            ],
            options={
                'db_table': 'argocdom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArgoChla',
            fields=[
                ('platform_number', models.IntegerField(primary_key=True, serialize=False)),
                ('cycle_number', models.IntegerField()),
                ('pressure', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True), size=None)),
                ('cpressure', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True), size=None)),
                ('qpressure', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1, null=True), size=None)),
                ('chla', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True), size=None)),
                ('cchla', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True), size=None)),
                ('qchla', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1, null=True), size=None)),
            ],
            options={
                'db_table': 'argochla',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArgoCore',
            fields=[
                ('platform_number', models.IntegerField()),
                ('cycle_number', models.IntegerField(primary_key=True, serialize=False)),
                ('pressure', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True), size=None)),
                ('cpressure', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True), size=None)),
                ('qpressure', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1, null=True), size=None)),
                ('temperature', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True), size=None)),
                ('ctemperature', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True), size=None)),
                ('qtemperature', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1, null=True), size=None)),
                ('salinity', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True), size=None)),
                ('csalinity', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True), size=None)),
                ('qsalinity', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1, null=True), size=None)),
            ],
            options={
                'db_table': 'argocore',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArgoDoxy',
            fields=[
                ('platform_number', models.IntegerField(primary_key=True, serialize=False)),
                ('cycle_number', models.IntegerField()),
                ('pressure', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True), size=None)),
                ('cpressure', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True), size=None)),
                ('qpressure', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1, null=True), size=None)),
                ('tempdoxy', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True), size=None)),
                ('ctempdoxy', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True), size=None)),
                ('qtempdoxy', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1, null=True), size=None)),
                ('doxygen', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True), size=None)),
                ('cdoxygen', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True), size=None)),
                ('qdoxygen', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1, null=True), size=None)),
            ],
            options={
                'db_table': 'argodoxy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArgoFloat',
            fields=[
                ('platform_number', models.IntegerField(primary_key=True, serialize=False)),
                ('transmission_system', models.CharField(blank=True, max_length=8, null=True)),
                ('postioning_system', models.CharField(blank=True, max_length=16, null=True)),
                ('platform_model', models.CharField(blank=True, max_length=16, null=True)),
                ('platform_maker', models.CharField(blank=True, max_length=24, null=True)),
                ('fireware_version', models.CharField(blank=True, max_length=32, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=8, null=True)),
                ('maual_version', models.CharField(blank=True, max_length=16, null=True)),
                ('wmo_type', models.CharField(blank=True, max_length=3, null=True)),
                ('project_name', models.CharField(blank=True, max_length=64, null=True)),
                ('pi_name', models.CharField(blank=True, max_length=40, null=True)),
                ('data_center', models.CharField(blank=True, max_length=2, null=True)),
                ('launch_date', models.CharField(blank=True, max_length=14, null=True)),
                ('launch_latitude', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('launch_longitude', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('launch_platform', models.CharField(blank=True, max_length=24, null=True)),
                ('park_pressure', models.IntegerField(blank=True, null=True)),
                ('profile_pressure', models.IntegerField(blank=True, null=True)),
                ('startup_date', models.CharField(blank=True, max_length=14, null=True)),
                ('cruise_id', models.CharField(blank=True, max_length=32, null=True)),
                ('float_status', models.BooleanField(blank=True, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'argofloat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArgoHeader',
            fields=[
                ('platform_number', models.IntegerField(primary_key=True, serialize=False)),
                ('cycle_number', models.IntegerField()),
                ('date_creation', models.DateTimeField()),
                ('project_name', models.CharField(max_length=255)),
                ('pi_name', models.CharField(max_length=255)),
                ('instrument_type', models.CharField(max_length=255)),
                ('sample_direction', models.CharField(max_length=1)),
                ('data_mode', models.CharField(max_length=1)),
                ('julian_day', models.FloatField()),
                ('date', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'argoheader',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArgoIrra',
            fields=[
                ('platform_number', models.IntegerField(primary_key=True, serialize=False)),
                ('cycle_number', models.IntegerField()),
                ('pressure', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True), size=None)),
                ('cpressure', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True), size=None)),
                ('qpressure', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1, null=True), size=None)),
                ('downirra412', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, db_column='downIrra412', decimal_places=6, max_digits=12, null=True), size=None)),
                ('cdownirra412', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, db_column='cdownIrra412', decimal_places=6, max_digits=12, null=True), size=None)),
                ('qdownirra412', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, db_column='qdownIrra412', max_length=1, null=True), size=None)),
                ('downirra443', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, db_column='downIrra443', decimal_places=6, max_digits=12, null=True), size=None)),
                ('cdownirra443', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, db_column='cdownIrra443', decimal_places=6, max_digits=12, null=True), size=None)),
                ('qdownirra443', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, db_column='qdownIrra443', max_length=1, null=True), size=None)),
                ('downirra490', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, db_column='downIrra490', decimal_places=6, max_digits=12, null=True), size=None)),
                ('cdownirra490', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, db_column='cdownIrra490', decimal_places=6, max_digits=12, null=True), size=None)),
                ('qdownirra490', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, db_column='qdownIrra490', max_length=1, null=True), size=None)),
                ('par', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True), size=None)),
                ('cpar', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True), size=None)),
                ('qpar', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1, null=True), size=None)),
            ],
            options={
                'db_table': 'argoirra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArgoNitr',
            fields=[
                ('platform_number', models.IntegerField(primary_key=True, serialize=False)),
                ('cycle_number', models.IntegerField()),
                ('pressure', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True), size=None)),
                ('cpressure', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True), size=None)),
                ('qpressure', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1, null=True), size=None)),
                ('nitrate', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True), size=None)),
                ('cnitrate', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True), size=None)),
                ('qnitrate', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1, null=True), size=None)),
            ],
            options={
                'db_table': 'argonitr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArgoPh',
            fields=[
                ('platform_number', models.IntegerField(primary_key=True, serialize=False)),
                ('cycle_number', models.IntegerField()),
                ('pressure', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True), size=None)),
                ('cpressure', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True), size=None)),
                ('qpressure', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1, null=True), size=None)),
                ('ph', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True), size=None)),
                ('cph', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True), size=None)),
                ('qph', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1, null=True), size=None)),
            ],
            options={
                'db_table': 'argoph',
                'managed': False,
            },
        ),
    ]
